#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build build-padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
    branches: 
      - master
  #schedule:
   # - cron: 0 19 * * *
  watch:
    types: [started]
    
env:
  DOWN_TOOLCHAIN: true
  TOOLCHAIN_URL: https://github.com/hminid/Padavan-ng_MI3_Build/releases/download/V20210510/toolchain_out.tar.gz

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: 检出非稳定版代码
      uses: actions/checkout@master
    - name: 初始化构建环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "::warning 非稳定版"
        echo "###########################"
        pwd
        #
        sudo mv Btools /opt/
        cd /opt/Btools
        echo "sudo ls -l"
        pwd
        sudo ls -l
        echo "###########################"
        #
        sudo apt-get update
        sudo apt-get -y install autoconf autoconf-archive automake autopoint bison build-essential ca-certificates cmake cpio curl doxygen fakeroot flex gawk gettext git gperf help2man htop kmod libblkid-dev libc-ares-dev libcurl4-openssl-dev libdevmapper-dev libev-dev libevent-dev libexif-dev libflac-dev libgmp3-dev libid3tag0-dev libidn2-dev libjpeg-dev libkeyutils-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libogg-dev libsqlite3-dev libssl-dev libtool libtool-bin libudev-dev libunbound-dev libvorbis-dev libxml2-dev locales mc nano pkg-config ppp-dev python3 python3-docutils sshpass texinfo unzip uuid uuid-dev vim wget xxd zlib1g-dev
    - name: 克隆源码
      run: |
        git clone -b master --depth=1 https://github.com/monw/padavan-ng.git /opt/rt-n56u
    - name: 自定义修改
      run: |
        sed -i 's/{ "wl_auth_mode", "psk" },/{ "wl_auth_mode", "open" },/g' /opt/rt-n56u/trunk/user/shared/defaults.c
        sed -i 's/{ "rt_auth_mode", "psk" },/{ "rt_auth_mode", "open" },/g' /opt/rt-n56u/trunk/user/shared/defaults.c
        sed -i 's/my.router/p.to/g' /opt/rt-n56u/trunk/user/rc/net_wan.c  
        sed -i '22a\ #define DEF_NTP_SERVER2 "pool.ntp.org" \n#define DEF_NTP_SERVER3 "pool.ntp.org"' /opt/rt-n56u/trunk/user/shared/defaults.c
        mkdir -p /opt/images/
        #
        cd /opt/Btools/Setconfig/
        sh install_Setconfig.sh
        #
         cd /opt/Btools/LANG_CN/
         sh install_LANG_CN.sh
        #
        #cd /opt/Btools/Theme/
        #sh install_Theme.sh
        
    - name: 准备工具链
      run: |
        if [ $DOWN_TOOLCHAIN = false ] ; then
           # 构建工具链
           cd /opt/rt-n56u/toolchain
           sudo ./clean_sources.sh
           sudo ./build_toolchain.sh
         else
           # 下载预编译的构建工具链
           cd /opt/rt-n56u/toolchain
           sh dl_toolchain.sh
        fi
        
    - name: 构建固件
      run: |
        cd /opt/rt-n56u/trunk
        sudo ./clear_tree.sh
        sudo ./build_firmware.sh
        sudo mv -f images/*.trx /opt/images/
    - name : 上传固件GitHub
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
        
    - name: 上传到发布
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: Padavan-NG
        files: /opt/images/*

    - name: 上传到WeTransfer
      if: always()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress /opt/images 2>&1 | tee wetransfer.log
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
